#!/bin/bash
#
# Copyright (C) 2020-2021 by Arya Zakaria, < https://github.com/aryazakaria01 >.
#
# This file is part of < https://github.com/aryazakaria01/Yuii-Dev > project,
# and is released under the "GNU v3.0 License Agreement".
# Please see < https://github.com/aryazakaria01/Yuii-Dev/blob/master/LICENSE >
#
# All rights reserved.

. init/proc.sh

declare -ir usr1=138
declare -r cmd='. init/init.sh; runYuii "$@"'

run() {
    reInitProc
    bash -c "$cmd" $0 "$@" &
    setProc $!
    waitProc
    test $? -eq $usr1 && run "$@"
}

run "$@"
